### ISSUE TITLE
Ability to override routes declared by packages in the app

### ISSUE THREAD

**Issue by rustamwin** [yiisoft/app#46] opened 2020-08-15 19:11 UTC
Currently, the routes located in config/routes.php, but that shouldn't be there.

**Comment by samdark** [comment] 2020-12-28 13:01
The issue is actually about ability to override routes declared by packages in the app.

**Comment by yiiliveext** [comment] 2021-03-05 08:08
Resolved by https://github.com/yiisoft/router/commit/374c5c898afdb857a03fae5ddd4a230c45c95974

**Closed** 2021-03-05 08:08 UTC
Labels: status:under discussion
